version: '2.3'

services:
  task:
    build: service
    restart: always
    volumes:
      - ./service/logs/:/var/log/gunicorn/
  nginx:
    image: nginx
    restart: always
    ports:
      - 33044:80
    depends_on:
      - task
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/logs/:/var/log/nginx/
