version: '2.3'

services:
  task:
    image: nginx
    restart: always
    ports:
      - 33014:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./service/:/var/www/:ro
